services:
  # Just the main database
  db:
    image: postgres:18.1
    container_name: dine_map_db
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:Z

  # Downloads raster tiles and generates vector tiles from them
  tile-generator:
    build:
      context: .
      dockerfile: Dockerfile.tiles
    image: anguspllg/dine-map-tile-generator
    container_name: dine_map_tile_generator
    env_file:
      - .env
    volumes:
      - ./tileset:/tileset:Z

  # Serves vector tiles using MapTiler's tileserver-gl
  tileserver:
    image: maptiler/tileserver-gl
    container_name: dine_map_tileserver
    restart: unless-stopped
    depends_on:
      tile-generator:
        condition: service_completed_successfully
    volumes:
      - ./tileset:/data:Z
    command: -c /data/config.json
    ports:
      - '${TILES_PORT}:8080'

volumes:
  pg_data:
